-- =========================================================
-- Slice-9 cutover (0018): users.role_id NOT NULL + drop legacy authorization
-- =========================================================
-- Generated by drizzle-kit (0017 -> schema cutover) and then hand-completed
-- with a deliberate, idempotent backfill plus fail-fast preflight checks:
--
-- drizzle-kit cannot express data backfill, and the raw diff would fail on
-- any pre-cutover row: `user.role_id` is still NULL for users whose Role was
-- only represented by the legacy `user.role` key, and the legacy column is
-- needed as the backfill source. Statement order below is therefore:
--
--   0. Preflight (fail-fast, before any write; the whole migration runs in
--      one transaction, so a raised exception aborts it atomically):
--      a. Reserved system keys: any `admin_role` row whose `key` is one of
--         the code-owned keys ('system_owner', 'hq', 'admin') must BE the
--         expected system Role identity — is_system true, not archived, and
--         the canonical Name ('System Owner' / 'HQ' / 'Admin', compared
--         under the canonical normalization below). Otherwise the system
--         insert below (`ON CONFLICT ("key") DO NOTHING`) would silently
--         attach Initial-Role grants and backfilled users to an arbitrary
--         custom Role squatting the key.
--      b. Normalized-Name collisions with the reserved Names: any
--         `admin_role` row that is NOT one of the three code-owned system
--         Roles must not canonically normalize (trim + whitespace collapse
--         + lowercase — exactly the recreated
--         `admin_role_name_normalized_unique` expression and the
--         application's normalizeRoleName) to 'system owner', 'hq' or
--         'admin'. Otherwise the system-Role insert below would violate
--         that unique index mid-migration with a cryptic error.
--      c. Duplicate normalized Names: two existing rows that share one
--         canonical normalization would ALSO violate the recreated unique
--         index — caught here with a readable error instead.
--      d. Unexpected legacy roles: every non-null `user.role` value must
--         canonically normalize (trim + whitespace collapse + lowercase) to
--         'hq' or 'admin'. Anything else (stale pre-monorepo
--         'customer'/'staff' rows, typos, junk) aborts the migration with
--         the offending values listed — unexpected values are NOT silently
--         translated.
--   1. Recreate `admin_role_name_normalized_unique` with the canonical
--      expression. 0017 already applied the index with an untrimmed
--      expression (lower + whitespace collapse only); drizzle-kit cannot
--      express expression-index repairs on applied migrations, so the drop/
--      recreate happens here, after the preflights and before the
--      system-Role insert, so the seeded Names satisfy the recreated index.
--   2. Ensure the code-owned system Roles exist (idempotent, same shape as
--      packages/db/src/rbac/seed-defaults.ts / ensure-roles.ts) so every
--      legacy key has a safe FK target. Existing Role rows are never
--      modified — only missing rows are inserted.
--   3. Repair missing Initial-Role grant rows for system_owner/hq/admin
--      (idempotent, mirrors ensureInitialRoles) so backfilled users are not
--      silently deny-all.
--   4. Backfill `user.role_id` from the legacy `user.role` key with the
--      SAME canonical normalization (lower(btrim(regexp_replace(role,
--      '\s+', ' ', 'g')))): 'hq' -> system Role 'hq'; anything else falls
--      back to the least-privilege 'admin' Role (never 'hq' — a misread
--      must not grant escalation). After preflight (0d) passed, only
--      'hq'/'admin' remain, so the fallback is a belt-and-braces safety
--      net, not silent translation of foreign values.
--   5. Assert no NULL `user.role_id` remains, then enforce NOT NULL.
--   6. Drop the legacy `user.role` column (IF EXISTS — recovery-safe on a
--      partially repaired database).
--   7. Drop the legacy `permission` table. DELIBERATELY WITHOUT CASCADE and
--      without translating legacy permission customization: the confirmed
--      plan replaces runtime-editable `permission` rows with normalized
--      Initial-Role grants (HQ: full/all-branch; Admin: least-privilege
--      own-branch). Any per-Admin permission tuning done through
--      /api/admin/permissions during the maintenance window is intentionally
--      DISCARDED — it must be re-expressed as a custom Role via the new
--      Roles UI after cutover. The plain DROP (no CASCADE) fails loudly if
--      some unforeseen object still references `permission`, instead of
--      destroying it; IF EXISTS keeps re-runs after manual recovery safe.
--
-- Maintenance window: schema migration and code deploy are one paired step
-- and there is no dual-read/write compatibility path by design. Rollback is
-- a paired operation: restore the pre-cutover pg_dump backup and redeploy
-- the previous image.
--
-- FKs (`user_role_id_admin_role_id_fk` RESTRICT,
-- `admin_role_grant_role_id_... CASCADE`) and all business data are
-- untouched by this migration; the ONLY dropped object is the pinned
-- normalized-Name index, recreated below with the corrected expression.
--> statement-breakpoint
DO $preflight$
DECLARE
  offenders text;
BEGIN
  SELECT string_agg(format('%s ("key" = %s)', "name", quote_literal("key")), ', ' ORDER BY "key")
    INTO offenders
  FROM "admin_role"
  WHERE "key" IN ('system_owner', 'hq', 'admin')
    AND NOT (
      "is_system" IS TRUE
      AND "archived_at" IS NULL
      AND lower(btrim(regexp_replace("name", '\s+', ' ', 'g'))) = CASE "key"
        WHEN 'system_owner' THEN 'system owner'
        WHEN 'hq' THEN 'hq'
        WHEN 'admin' THEN 'admin'
      END
    );
  IF offenders IS NOT NULL THEN
    RAISE EXCEPTION USING MESSAGE = format(
      'migration 0018 preflight: reserved system key held by a row that is not the expected system Role identity (is_system true, not archived, canonical Name System Owner / HQ / Admin): %s. Delete or repair the squatter row(s) before the cutover — the idempotent system-Role insert (ON CONFLICT ("key") DO NOTHING) would otherwise attach Initial-Role grants and backfilled users to the wrong Role.',
      offenders
    );
  END IF;
END
$preflight$;--> statement-breakpoint
DO $preflight$
DECLARE
  collisions text;
BEGIN
  -- COALESCE the key: a keyless custom Role ("key" IS NULL) would otherwise
  -- NULL out the whole concatenation and silently evade this preflight.
  SELECT string_agg(COALESCE('"' || "key" || '" ', '') || '("' || "name" || '")', ', ')
    INTO collisions
  FROM "admin_role"
  WHERE ("key" IS NULL OR "key" NOT IN ('system_owner', 'hq', 'admin'))
    AND lower(btrim(regexp_replace("name", '\s+', ' ', 'g')))
        IN ('system owner', 'hq', 'admin');
  IF collisions IS NOT NULL THEN
    RAISE EXCEPTION USING MESSAGE = format(
      'migration 0018 preflight: normalized Role-Name collision with the reserved Initial-Role Names (System Owner / HQ / Admin): %s. Rename the listed Role(s) before the cutover — inserting the system Roles would violate admin_role_name_normalized_unique.',
      collisions
    );
  END IF;
END
$preflight$;--> statement-breakpoint
DO $preflight$
DECLARE
  duplicates text;
BEGIN
  SELECT string_agg(format('%s: %s', norm, names), ', ')
    INTO duplicates
  FROM (
    SELECT lower(btrim(regexp_replace("name", '\s+', ' ', 'g'))) AS norm,
           string_agg('"' || "name" || '"', ', ') AS names
    FROM "admin_role"
    GROUP BY 1
    HAVING count(*) > 1
  ) d;
  IF duplicates IS NOT NULL THEN
    RAISE EXCEPTION USING MESSAGE = format(
      'migration 0018 preflight: duplicate normalized Role-Name(s) under the canonical normalization (trim + whitespace collapse + lowercase): %s. The recreated admin_role_name_normalized_unique index would reject these rows; rename them before the cutover.',
      duplicates
    );
  END IF;
END
$preflight$;--> statement-breakpoint
DO $preflight$
DECLARE
  unexpected text;
  has_legacy_role_column boolean;
BEGIN
  has_legacy_role_column :=
    to_regclass('public."user"') IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM pg_attribute
      WHERE attrelid = 'public."user"'::regclass
        AND attname = 'role'
        AND NOT attisdropped
    );
  IF has_legacy_role_column THEN
    SELECT string_agg(v, ', ')
      INTO unexpected
      FROM (
        SELECT DISTINCT lower(btrim(regexp_replace("role", '\s+', ' ', 'g'))) AS v
        FROM "user"
        WHERE "role" IS NOT NULL
          AND lower(btrim(regexp_replace("role", '\s+', ' ', 'g'))) NOT IN ('hq', 'admin')
      ) s;
    IF unexpected IS NOT NULL THEN
      RAISE EXCEPTION USING MESSAGE = format(
        'migration 0018 preflight: unexpected legacy user.role value(s): %s. Only ''hq'' or ''admin'' (case/whitespace-insensitive) are supported by the cutover backfill; unexpected values are NOT silently demoted to Admin. Reconcile these rows before running the cutover.',
        unexpected
      );
    END IF;
  END IF;
END
$preflight$;--> statement-breakpoint
DROP INDEX IF EXISTS "admin_role_name_normalized_unique";--> statement-breakpoint
CREATE UNIQUE INDEX "admin_role_name_normalized_unique" ON "admin_role" USING btree (lower(btrim(regexp_replace("name", '\s+', ' ', 'g'))));--> statement-breakpoint
INSERT INTO "admin_role" ("id", "key", "name", "description", "is_system", "version")
VALUES
  (gen_random_uuid()::text, 'system_owner', 'System Owner', NULL, true, 1),
  (gen_random_uuid()::text, 'hq', 'HQ', NULL, true, 1),
  (gen_random_uuid()::text, 'admin', 'Admin', NULL, true, 1)
ON CONFLICT ("key") DO NOTHING;--> statement-breakpoint
INSERT INTO "admin_role_grant" ("id", "role_id", "module", "action", "scope")
SELECT gen_random_uuid()::text, r."id", g."module", g."action", g."scope"
FROM (
  VALUES
    -- HQ seed grants (HQ_SEED_GRANTS — full, all-branch + global)
    ('hq', 'products', 'view', 'all_branches'),
    ('hq', 'products', 'edit', 'all_branches'),
    ('hq', 'orders', 'view', 'all_branches'),
    ('hq', 'orders', 'edit', 'all_branches'),
    ('hq', 'notifications', 'view', 'all_branches'),
    ('hq', 'notifications', 'edit', 'all_branches'),
    ('hq', 'notifications', 'delete', 'all_branches'),
    ('hq', 'branches', 'view', 'all_branches'),
    ('hq', 'branches', 'edit', 'all_branches'),
    ('hq', 'branches', 'delete', 'all_branches'),
    ('hq', 'analytics', 'view', 'all_branches'),
    ('hq', 'audit_log', 'view', 'all_branches'),
    ('hq', 'customers', 'view', 'global'),
    ('hq', 'homepage', 'view', 'global'),
    ('hq', 'homepage', 'edit', 'global'),
    ('hq', 'homepage', 'delete', 'global'),
    ('hq', 'pages', 'view', 'global'),
    ('hq', 'pages', 'edit', 'global'),
    ('hq', 'pages', 'delete', 'global'),
    ('hq', 'users', 'view', 'global'),
    ('hq', 'users', 'edit', 'global'),
    ('hq', 'users', 'delete', 'global'),
    ('hq', 'roles', 'view', 'global'),
    ('hq', 'roles', 'edit', 'global'),
    ('hq', 'roles', 'delete', 'global'),
    ('hq', 'footer', 'view', 'global'),
    ('hq', 'footer', 'edit', 'global'),
    -- Admin seed grants (ADMIN_SEED_GRANTS — least-privilege, own branch)
    ('admin', 'products', 'view', 'own_branch'),
    ('admin', 'orders', 'view', 'own_branch'),
    ('admin', 'orders', 'edit', 'own_branch'),
    ('admin', 'notifications', 'view', 'own_branch'),
    ('admin', 'notifications', 'edit', 'own_branch'),
    ('admin', 'notifications', 'delete', 'own_branch')
) AS g("key", "module", "action", "scope")
JOIN "admin_role" r ON r."key" = g."key"
WHERE NOT EXISTS (
  SELECT 1 FROM "admin_role_grant" x
  WHERE x."role_id" = r."id" AND x."module" = g."module" AND x."action" = g."action"
);--> statement-breakpoint
UPDATE "user" u
SET "role_id" = r."id"
FROM "admin_role" r
WHERE u."role_id" IS NULL
  AND r."key" = CASE
    WHEN lower(btrim(regexp_replace(u."role", '\s+', ' ', 'g'))) = 'hq' THEN 'hq'
    ELSE 'admin'
  END;--> statement-breakpoint
DO $assert$
DECLARE
  remaining integer;
BEGIN
  SELECT count(*) INTO remaining FROM "user" WHERE "role_id" IS NULL;
  IF remaining > 0 THEN
    RAISE EXCEPTION USING MESSAGE = format(
      'migration 0018 backfill incomplete: %s user row(s) still have role_id IS NULL after the legacy-role backfill; refusing to enforce NOT NULL. Investigate the legacy user.role values before retrying.',
      remaining
    );
  END IF;
END
$assert$;--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "role_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "user" DROP COLUMN IF EXISTS "role";--> statement-breakpoint
ALTER TABLE "permission" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE IF EXISTS "permission";